language: node_js
node_js:
- 10.4.0
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "${GH_TOKEN}"
  target-branch: gh-pages
  keep-history: true
  local-dir: public
  on:
    branch: master
