version: 2
# jobs
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0f:d0:9e:f9:da:a1:d4:74:9d:d1:47:68:1b:ff:ee:c1"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn add hexo-cli -g
      - run: yarn sync
      - run: yarn deploy
