version: 2
# jobs
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn add hexo-cli -g
      - run: yarn add hexo -g
      - run: hexo g
