version: 2
# jobs
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0f:d0:9e:f9:da:a1:d4:74:9d:d1:47:68:1b:ff:ee:c1"
            - "20:15:f7:94:e8:1c:fb:a0:90:db:27:6d:af:de:bc:ea"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: submodules
          command:
            git config --global user.email "deploy@zhuweisheng.com.cn"
            git config --global user.name "deployRobot"
            git submodule init
            git submodule update
            git submodule foreach git pull origin master
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn add hexo-cli -g
      - run: yarn deploy
